<a href="https://colab.research.google.com/github/GabriellaPompeu/Learning-Pytorch/blob/main/IntroToColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**
*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   default data type of float32.
* is more suitable for deep learning than a numpy array.



In [3]:
import torch
import numpy as np

In [10]:
# Create a tensor 2-D with random values
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.9759,  0.2158,  2.8399, -1.2053],
        [ 0.4678,  0.3057,  1.3371, -0.6119],
        [-0.0916, -0.7740, -0.6892, -0.2520]])

In [11]:
# Create a tensor 3-D with zeros
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape and View
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [16]:
# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(14)
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [22]:
my_torch3 = torch.randn(10)
my_torch3 = my_torch3.reshape(2, 5)
my_torch3

tensor([[ 0.3303, -0.2169,  0.7087,  0.2596, -0.0982],
        [-0.4213,  0.4503,  0.5515, -0.1787, -0.0478]])

In [23]:
tensor_res = torch.add(my_torch, my_torch3)
tensor_res

tensor([[0.3303, 0.7831, 2.7087, 3.2596, 3.9018],
        [4.5787, 6.4503, 7.5515, 7.8213, 8.9522]])